### ISSUE TITLE
BottomNavigation: Support for hiding on scroll

### ISSUE THREAD

**Issue by codypearce** [codypearce/material-bread#24]
**Describe your feature request**
Material docs shows bottom navigation hiding on scrolling down and showing on scroll up. 

**Context**
https://material.io/design/components/bottom-navigation.html#behavior

<img width="790" alt="Bottom navigation - Material Design 2019-04-19 03-20-15" src="https://user-images.githubusercontent.com/12564956/56420322-58e8c180-6252-11e9-98fa-c43a9ec85098.png">

**Todo**

- [ ] Create prop to toggle this behavior
- [ ] Update prop table
- [ ] Add storybook story for this functionality
