### ISSUE TITLE
Button: Add more storybook demos

### ISSUE THREAD

**Issue by codypearce** [codypearce/material-bread#28]
**Describe your feature request**
Currently each type of button has one example of various functional (loading, icons) etc. This should be increased. Each functionality should be on it's own line and have more demos. This could be broken into separate sections within each button type or with text in the story.

**Todo**
- [ ] Add more demos to Text Button
- [ ] Add more demos to Outlined Button
- [ ] Add more demos to Flat button
- [ ] Add more demos to Contained Button
