### ISSUE TITLE
[New Component]: Collapsible

### ISSUE THREAD

**Issue by codypearce** [codypearce/material-bread#30]
**Describe your feature request**
Create a component that will wrap arbitrary content and expand and collapse based on a visible prop. Material docs shows this functionality in various places.

**Context**
For example in the cards section https://material.io/design/components/cards.html#anatomy
![image](https://user-images.githubusercontent.com/12564956/56421057-9438bf80-6255-11e9-81fe-f49dbcf0f286.png)

**Todo**
- [ ] Create Collapse component
- [ ] Create storybook story
- [ ] Create doc page
- [ ] Create props table
- [ ] Create doc demo 
- [ ] Add Card demo as shown in material docs
- [ ] Add jest tests
