### ISSUE TITLE
Card: Support Transition to full screen card

### ISSUE THREAD

**Issue by codypearce** [codypearce/material-bread#31]
**Describe your feature request**
Material Docs shows a transition to a fullscreen card, that grows from the center and takes over the screen. 

**Context**
https://material.io/design/components/cards.html#behavior

![image](https://user-images.githubusercontent.com/12564956/56421190-293bb880-6256-11e9-9c6d-95a1fc4fc2ac.png)

**Proposed solution**
Maybe add a prop for `isFullScreen` or something that can be toggled. Demos should replace the inner children to reproduce the top commands seen in the docs, with the close icon.

**Todo**

- [ ] Add prop for toggling
- [ ] Create functionality
- [ ] Update Prop table
- [ ] Add storybook story section
- [ ] Add doc demo
