### ISSUE TITLE
Card: Create more Storybook demos

### ISSUE THREAD

**Issue by codypearce** [codypearce/material-bread#34]
**Describe your feature request**
Currently there are only a few card demos in storybook.  Add some more demos for example some small and thin ones.

It should also be separated out into different sections

- Simple
- Full
- Clickable

**Context**
https://codypearce.github.io/material-bread/?path=/story/components-card--card

![image](https://user-images.githubusercontent.com/12564956/56421548-e8dd3a00-6257-11e9-8481-61378e92ef2c.png)

**Todo**
- [x] Add more demos to the card section in storybook
- [x] Create simple section
- [x] Create full section
- [x] Creat clickable section
